### PR TITLE
Clean patch

### PR DESCRIPTION
**Pull request by VegetalDev**

### CODE REVIEW

**Comment by tachibanayui** [comment]
This prob not necessary anymore so I will close this for now

**Comment by VegetalDev** [comment]
true

**Comment by tachibanayui** [comment]
Actually, it might be necessary. But maybe we should add `f.name.startsWith(project.pluginDir)` so it doesn't clean other plugins. The idea of `clean-plugin` (no plural) tasks is to remove older versions of this plugin, not other plugins old files. Also, this task is kinda unnecessary since the local version won't automatically increase

**Comment by VegetalDev** [comment]
> 
> 
> Actually, it might be necessary. But maybe we should add `f.name.startsWith(project.pluginDir)` so it doesn't clean other plugins. The idea of `clean-plugin` (no plural) tasks is to remove older versions of this plugin, not other plugins old files. Also, this task is kinda unnecessary since the local version won't automatically increase

well, f.name.startsWith(project.pluginDir) doesn't work - project.pluginDir is usually something like "C:\Users\User\IdeaProjects\run\server-1\plugins"; and f.name is just the name of the file (it doesn't include the path)

**Comment by tachibanayui** [comment]
Oh my bad, I meant project.name

**Comment by VegetalDev** [comment]
project.name works,  but it won't clean other plugins that we need cleared (like arena-api). example: you update your arena-api version, but because we're using project.name, the old arena-api jar will not get deleted

**Comment by tachibanayui** [comment]
We should make another task for that use case

**Comment by tachibanayui** [comment]
Clearing other plugins is kinda put stress to our storage, especially developer with ssd

**Comment by VegetalDev** [comment]
but it's also super necessary as you shouldn't have to manually delete previous versions when updating
also gradle probably deletes and re-creates files all the time over the course of normal development regardless

**Comment by tachibanayui** [comment]
Actually gradle check for update, if there isn't a need for update then gradle will not execute that task.

**Comment by VegetalDev** [comment]
still i don't think that deleting and re-creating a few jar files is going to put much strain on anyone's SSD

**Comment by tachibanayui** [comment]
SSDs have a strict write limit (60 to 150TB) over it lifetime. It won't be an issue for a short time but it will add up overtime. Eg. Mythic jar is over 18mb. Also re copying them will slowdown build for crappy drive. 


For ease of use when upgrading version, we could create a new task and run configuration for it, or even better checking version and delete old one inside copyPlugin task

**Comment by VegetalDev** [comment]
> 
> 
> SSDs have a strict write limit (60 to 150TB) over it lifetime. It won't be an issue for a short time but it will add up overtime. Eg. Mythic jar is over 18mb. Also re copying them will slowdown build for crappy drive.
> 
> For ease of use when upgrading version, we could create a new task and run configuration for it, or even better checking version and delete old one inside copyPlugin task

i think i prefer just doing version checking in copyPlugin, but a new task is fine too

**Comment by tachibanayui** [comment]
T, cool and good

**Comment by tachibanayui** [comment]
prob close this again since we have a new clean task in #2

**Pull request closed without merging**
